<?php
namespace Database\Seeders;
use App\Models\War;
use Illuminate\Database\Seeder;
class WarSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['nama' => 'Perang Bubat', 'tahun' => '1357', 'wilayah' => 'Bubat, Jawa Timur (Trowulan)', 'matra' => 'darat', 'kategori' => 'Perang Era Kerajaan', 'pop' => 200000, 'lat' => -7.55, 'lon' => 112.38, 'deskripsi' => 'Konflik Majapahit vs Kerajaan Sunda (Pasunda Bubat) di alun-alun Trowulan.'],
            ['nama' => 'Perang Paregreg', 'tahun' => '1404-1406', 'wilayah' => 'Majapahit, Jawa Timur', 'matra' => 'darat', 'kategori' => 'Perang Saudara', 'pop' => 300000, 'lat' => -7.55, 'lon' => 112.38, 'deskripsi' => 'Perang saudara Majapahit antara Bhre Wirabhumi dan Wikramawardhana.'],
            ['nama' => 'Perang Demak-Majapahit', 'tahun' => '1527', 'wilayah' => 'Demak - Majapahit, Jawa Timur', 'matra' => 'darat', 'kategori' => 'Perang Era Kerajaan', 'pop' => 220000, 'lat' => -6.89, 'lon' => 110.63, 'deskripsi' => 'Ekspedisi Kesultanan Demak menguasai sisa Majapahit.'],
            ['nama' => 'Perang Aceh', 'tahun' => '1873-1904', 'wilayah' => 'Aceh, Sumatera', 'matra' => 'gabungan', 'kategori' => 'Perlawanan Kolonial', 'pop' => 500000, 'lat' => 5.55, 'lon' => 95.32, 'deskripsi' => 'Perlawanan Kesultanan Aceh vs Belanda — perang terlama dan terbesar di Nusantara.'],
            ['nama' => 'Perang Padri', 'tahun' => '1803-1837', 'wilayah' => 'Minangkabau, Sumatera Barat', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 350000, 'lat' => -0.55, 'lon' => 100.5, 'deskripsi' => 'Perang saudara kaum Padri hingga Belanda turun tangan.'],
            ['nama' => 'Perang Diponegoro', 'tahun' => '1825-1830', 'wilayah' => 'Jogja - Surakarta, Jawa Tengah', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 500000, 'lat' => -7.79, 'lon' => 110.36, 'deskripsi' => 'Perang Jawa Pangeran Diponegoro — perlawanan terbesar abad 19.'],
            ['nama' => 'Perang Banjar', 'tahun' => '1859-1905', 'wilayah' => 'Kalimantan Selatan', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 250000, 'lat' => -3.35, 'lon' => 114.6, 'deskripsi' => 'Perlawanan Kesultanan Banjar vs Belanda (Pangeran Antasari).'],
            ['nama' => 'Perang Bali (Ekspedisi)', 'tahun' => '1846-1849', 'wilayah' => 'Bali', 'matra' => 'gabungan', 'kategori' => 'Perlawanan Kolonial', 'pop' => 150000, 'lat' => -8.36, 'lon' => 115.13, 'deskripsi' => 'Ekspedisi Belanda ke Buleleng, Jagaraga, dan badung.'],
            ['nama' => 'Perang Jagaraga', 'tahun' => '1848-1849', 'wilayah' => 'Jagaraga, Buleleng, Bali', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 100000, 'lat' => -8.1, 'lon' => 115.09, 'deskripsi' => 'Puputan Buleleng — pertempuran habis-habisan di benteng Jagaraga.'],
            ['nama' => 'Perang Puputan Badung', 'tahun' => '1906', 'wilayah' => 'Badung, Bali Selatan', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 90000, 'lat' => -8.65, 'lon' => 115.21, 'deskripsi' => 'Puputan (perang habis-habisan) Badung vs Belanda.'],
            ['nama' => 'Perang Puputan Klungkung', 'tahun' => '1908', 'wilayah' => 'Klungkung, Bali', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 80000, 'lat' => -8.54, 'lon' => 115.41, 'deskripsi' => 'Puputan Klungkung — penyerahan terakhir Bali ke Belanda.'],
            ['nama' => 'Perang Sisingamangaraja', 'tahun' => '1878-1907', 'wilayah' => 'Tapanuli, Sumatera Utara', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 200000, 'lat' => 1.99, 'lon' => 99.25, 'deskripsi' => 'Perlawanan rakyat Batak pimpinan Sisingamangaraja XII.'],
            ['nama' => 'Perang Batak', 'tahun' => '1878-1907', 'wilayah' => 'Tanah Batak, Sumatera Utara', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 200000, 'lat' => 1.99, 'lon' => 99.25, 'deskripsi' => 'Gelombang perlawanan di tanah Batak terhadap kompeni.'],
            ['nama' => 'Perang Makassar', 'tahun' => '1660-1669', 'wilayah' => 'Gowa-Tallo, Sulawesi Selatan', 'matra' => 'gabungan', 'kategori' => 'Perlawanan Kolonial', 'pop' => 300000, 'lat' => -5.15, 'lon' => 119.43, 'deskripsi' => 'Perlawanan Sultan Hasanuddin (Ayam Jantan Timur) vs Belanda.'],
            ['nama' => 'Perang Tondano', 'tahun' => '1808-1809', 'wilayah' => 'Minahasa, Sulawesi Utara', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 120000, 'lat' => 1.3, 'lon' => 124.9, 'deskripsi' => 'Perlawanan rakyat Tondano terhadap kerja rodi Belanda.'],
            ['nama' => 'Perang Jawa', 'tahun' => '1837', 'wilayah' => 'Jawa Timur', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 400000, 'lat' => -7.8, 'lon' => 112.03, 'deskripsi' => 'Perlawanan di Kediri dan kawasan Jawa Timur.'],
            ['nama' => 'Perang Lombok', 'tahun' => '1894', 'wilayah' => 'Lombok, NTB', 'matra' => 'gabungan', 'kategori' => 'Perlawanan Kolonial', 'pop' => 180000, 'lat' => -8.65, 'lon' => 116.32, 'deskripsi' => 'Ekspedisi Belanda ke Lombok (Cakranagara).'],
            ['nama' => 'Perang Bone', 'tahun' => '1824-1905', 'wilayah' => 'Sulawesi Selatan', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 150000, 'lat' => -4.53, 'lon' => 120.29, 'deskripsi' => 'Perlawanan panjang Kesultanan Bone melawan Belanda.'],
            ['nama' => 'Perang Palembang', 'tahun' => '1819-1821', 'wilayah' => 'Palembang, Sumatera Selatan', 'matra' => 'laut', 'kategori' => 'Perlawanan Kolonial', 'pop' => 160000, 'lat' => -2.99, 'lon' => 104.75, 'deskripsi' => 'Serangan militer Belanda ke Kesultanan Palembang (Sultan Mahmud).'],
            ['nama' => 'Perang Pattimura', 'tahun' => '1817', 'wilayah' => 'Saparua, Maluku Tengah', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 100000, 'lat' => -3.78, 'lon' => 128.64, 'deskripsi' => 'Perlawanan Kapitan Pattimura di Saparua, Maluku.'],
            ['nama' => 'Perang Diponegoro II', 'tahun' => '1825', 'wilayah' => 'Jawa Tengah', 'matra' => 'darat', 'kategori' => 'Perlawanan Kolonial', 'pop' => 500000, 'lat' => -7.79, 'lon' => 110.36, 'deskripsi' => 'Ekses lanjutan Perlawanan Pangeran Diponegoro.'],
            ['nama' => 'Perang Gerilya Jend. Sudirman', 'tahun' => '1948-1949', 'wilayah' => 'Jawa Tengah - Selatan', 'matra' => 'darat', 'kategori' => 'Revolusi Nasional', 'pop' => 450000, 'lat' => -7.65, 'lon' => 109.06, 'deskripsi' => 'Perjalanan gerilya Jenderal Sudirman saat Agresi Militer Belanda II.'],
            ['nama' => 'Pertempuran Surabaya', 'tahun' => '1945', 'wilayah' => 'Surabaya, Jawa Timur', 'matra' => 'darat', 'kategori' => 'Revolusi Nasional', 'pop' => 600000, 'lat' => -7.25, 'lon' => 112.75, 'deskripsi' => 'Pertempuran 10 November 1945 — arek-arek Surabaya melawan Sekutu.'],
            ['nama' => 'Pertempuran Ambarawa', 'tahun' => '1945', 'wilayah' => 'Ambarawa, Jawa Tengah', 'matra' => 'darat', 'kategori' => 'Revolusi Nasional', 'pop' => 180000, 'lat' => -7.27, 'lon' => 110.39, 'deskripsi' => 'Pertempuran Palagan Ambarawa (12-15 Des 1945).'],
            ['nama' => 'Pertempuran Medan Area', 'tahun' => '1945-1946', 'wilayah' => 'Medan, Sumatera Utara', 'matra' => 'darat', 'kategori' => 'Revolusi Nasional', 'pop' => 250000, 'lat' => 3.59, 'lon' => 98.67, 'deskripsi' => 'Aksi pemuda Medan vs pasukan Belanda/NICA.'],
            ['nama' => 'Bandung Lautan Api', 'tahun' => '1946', 'wilayah' => 'Bandung, Jawa Barat', 'matra' => 'darat', 'kategori' => 'Revolusi Nasional', 'pop' => 400000, 'lat' => -6.91, 'lon' => 107.61, 'deskripsi' => 'Pembakaran Bandung Selatan oleh pejuang pada 24 Maret 1946.'],
            ['nama' => 'Pertempuran Lima Hari di Semarang', 'tahun' => '1945', 'wilayah' => 'Semarang, Jawa Tengah', 'matra' => 'darat', 'kategori' => 'Revolusi Nasional', 'pop' => 350000, 'lat' => -6.96, 'lon' => 110.42, 'deskripsi' => 'Pertempuran 15-19 Okt 1945 — gugurnya dr. Karyadi.'],
            ['nama' => 'Agresi Militer Belanda I', 'tahun' => '1947', 'wilayah' => 'Jawa & Sumatera', 'matra' => 'gabungan', 'kategori' => 'Revolusi Nasional', 'pop' => 900000, 'lat' => -7.5, 'lon' => 110.0, 'deskripsi' => 'Operasi Product Belanda (Juli 1947).'],
            ['nama' => 'Agresi Militer Belanda II', 'tahun' => '1948-1949', 'wilayah' => 'Jogja & Jawa Tengah', 'matra' => 'gabungan', 'kategori' => 'Revolusi Nasional', 'pop' => 750000, 'lat' => -7.79, 'lon' => 110.36, 'deskripsi' => 'Serangan ke Ibukota Yogja (19 Des 1948) — awal gerilya Sudirman.'],
            ['nama' => 'Perang Kemerdekaan Indonesia', 'tahun' => '1945-1949', 'wilayah' => 'Seluruh Indonesia', 'matra' => 'gabungan', 'kategori' => 'Revolusi Nasional', 'pop' => 2000000, 'lat' => -6.2, 'lon' => 106.8, 'deskripsi' => 'Revolusi nasional total — darat, laut, udara.'],
            ['nama' => 'Pemberontakan PKI Madiun', 'tahun' => '1948', 'wilayah' => 'Madiun, Jawa Timur', 'matra' => 'darat', 'kategori' => 'Pemberontakan Dalam Negeri', 'pop' => 150000, 'lat' => -7.62, 'lon' => 111.53, 'deskripsi' => 'Pemberontakan PKI Musso di Madiun.'],
            ['nama' => 'Pemberontakan DI/TII', 'tahun' => '1949-1962', 'wilayah' => 'Jabar & Sulsel', 'matra' => 'darat', 'kategori' => 'Pemberontakan Dalam Negeri', 'pop' => 300000, 'lat' => -6.91, 'lon' => 107.61, 'deskripsi' => 'Geraka DI/TII Kartosuwiryo & Kahar Muzakkar.'],
            ['nama' => 'Pemberontakan APRA', 'tahun' => '1950', 'wilayah' => 'Bandung, Jawa Barat', 'matra' => 'darat', 'kategori' => 'Pemberontakan Dalam Negeri', 'pop' => 100000, 'lat' => -6.91, 'lon' => 107.61, 'deskripsi' => 'Angkatan Perang Ratu Adil (APRA) kudeta Westerling.'],
            ['nama' => 'Pemberontakan Andi Azis', 'tahun' => '1950', 'wilayah' => 'Makassar, Sulawesi Selatan', 'matra' => 'darat', 'kategori' => 'Pemberontakan Dalam Negeri', 'pop' => 120000, 'lat' => -5.14, 'lon' => 119.43, 'deskripsi' => 'Kudeta Andi Azis di Makassar.'],
            ['nama' => 'Pemberontakan RMS', 'tahun' => '1950', 'wilayah' => 'Ambon, Maluku', 'matra' => 'darat', 'kategori' => 'Pemberontakan Dalam Negeri', 'pop' => 90000, 'lat' => -3.69, 'lon' => 128.17, 'deskripsi' => 'Republik Maluku Selatan (Soumokil).'],
            ['nama' => 'PRRI / Pemerintah Revolusioner', 'tahun' => '1958-1961', 'wilayah' => 'Bukittinggi, Sumatera Barat', 'matra' => 'darat', 'kategori' => 'Pemberontakan Dalam Negeri', 'pop' => 180000, 'lat' => -0.3, 'lon' => 100.36, 'deskripsi' => 'Pemerintahan Revolusioner RI di Sumatera Tengah.'],
            ['nama' => 'Permesta', 'tahun' => '1957-1961', 'wilayah' => 'Manado, Sulawesi Utara', 'matra' => 'gabungan', 'kategori' => 'Pemberontakan Dalam Negeri', 'pop' => 150000, 'lat' => 1.47, 'lon' => 124.85, 'deskripsi' => 'Permesta — operasi militer di Sulawesi Utara & Maluku.'],
            ['nama' => 'Operasi Trikora', 'tahun' => '1961-1962', 'wilayah' => 'Papua Barat', 'matra' => 'gabungan', 'kategori' => 'Operasi Militer Nasional', 'pop' => 400000, 'lat' => -4.0, 'lon' => 137.0, 'deskripsi' => 'Operasi pembebasan Irian Barat dari Belanda.'],
            ['nama' => 'Operasi Dwikora', 'tahun' => '1963-1966', 'wilayah' => 'Kalimantan Utara & Sarawak', 'matra' => 'gabungan', 'kategori' => 'Operasi Militer Nasional', 'pop' => 350000, 'lat' => 3.0, 'lon' => 114.0, 'deskripsi' => 'Konfrontasi dengan Malaysia — perang konvensional + non-tempur.'],
            ['nama' => 'Operasi Seroja', 'tahun' => '1975-1976', 'wilayah' => 'Timor Timur (Dili)', 'matra' => 'gabungan', 'kategori' => 'Operasi Militer Nasional', 'pop' => 250000, 'lat' => -8.5, 'lon' => 126.0, 'deskripsi' => 'Operasi integrasi di Timor Timur.'],
            ['nama' => 'Konflik Aceh', 'tahun' => '1976-2005', 'wilayah' => 'Aceh', 'matra' => 'gabungan', 'kategori' => 'Konflik Daerah', 'pop' => 400000, 'lat' => 5.0, 'lon' => 96.0, 'deskripsi' => 'Konflik separatisme GAM vs TNI/POLRI (MoU Helsinki 2005).'],
            ['nama' => 'Konflik Timor Timur', 'tahun' => '1976-1999', 'wilayah' => 'Timor Timur (Dili)', 'matra' => 'gabungan', 'kategori' => 'Konflik Daerah', 'pop' => 200000, 'lat' => -8.55, 'lon' => 125.56, 'deskripsi' => 'Konflik dan referendum 1999.'],
            ['nama' => 'Konflik Poso', 'tahun' => '1998-2001', 'wilayah' => 'Poso, Sulawesi Tengah', 'matra' => 'darat', 'kategori' => 'Konflik Daerah', 'pop' => 150000, 'lat' => -1.39, 'lon' => 120.76, 'deskripsi' => 'Konflik komunal Poso.'],
            ['nama' => 'Konflik Maluku', 'tahun' => '1999-2002', 'wilayah' => 'Ambon, Maluku', 'matra' => 'darat', 'kategori' => 'Konflik Daerah', 'pop' => 200000, 'lat' => -3.69, 'lon' => 128.17, 'deskripsi' => 'Konflik komunal Ambon.'],
            ['nama' => 'Konflik Papua', 'tahun' => '1962-sekarang', 'wilayah' => 'Papua & Papua Barat', 'matra' => 'gabungan', 'kategori' => 'Konflik Daerah', 'pop' => 500000, 'lat' => -4.0, 'lon' => 137.0, 'deskripsi' => 'Konflik separat OPM/TPNPB — operasi keamanan.'],
        ];

        foreach ($data as $d) {
            War::create($d);
        }
    }
}
